### ISSUE TITLE
Foreign key-derived sets are not strongly typed as they should

### ISSUE THREAD

**Issue by martinfr87** [stadler/hibernate-tools-maven-plugin#1]
I have noticed a difference between the files generated

- with hibernate-tools-maven-plugin
- with, eg., the JPA Tools of Eclipse.

Say we have the Northwind database, a Customers entity is generated:

```
@Entity
@Table(name="customers"
    ,schema="NORTHWIND"
    ,catalog="NORTHWIND"
)
public class Customers  implements java.io.Serializable {

     private Integer id;
     // [...]
     private Set<Orders> orderses = new HashSet<Orders>(0);
```

Notice the orderses member. It is not strongly-typed, as it should, when entity generation is done through hibernate-tools-maven-plugin.

It is strongly typed when entity generation is performed with JPA Tools:

`	private Set<Orders> orderses = new HashSet<Orders>(0);`

Will this be fixed in the 6.0.0 release?
BTW how to try the 6.0.0 release of the Maven plugin?

Please note: I can't open an Issue on https://github.com/hibernate/hibernate-tools as the Issue tab has not been enabled in this project.

**Comment by mmm8955405** [comment]
These two projects are garbage and have no documents

**Comment by stadler** [comment]
Hi
As mentioned in the README.md, this project is no longer active as it has been integrated into hibernate tools itself.
You may find the latest version of hibernate-tools here: https://github.com/hibernate/hibernate-tools
To create issues for hibernate-tools see: https://github.com/hibernate/hibernate-tools/blob/main/contribute.md

**Comment by mmm8955405** [comment]
> Hi As mentioned in the README.md, this project is no longer active as it has been integrated into hibernate tools itself. You may find the latest version of hibernate-tools here: https://github.com/hibernate/hibernate-tools To create issues for hibernate-tools see: https://github.com/hibernate/hibernate-tools/blob/main/contribute.md



I read a lot of documents,
I can set the output file name of dao through "filepattern" in maven intron plugin, as follows:
`<hbmtemplate
							   templatepath="${project.basedir}/src/main/resources/generate/jpa"
							   template="DaoHome.ftl"
							   filepattern="{package-name}/daos/{class-name}JpaDao.java">
							    <property key="jdk5" value="false" />
  								<property key="ejb3" value="false" />
							 </hbmtemplate>`
However, in the "hibernate tools maven" 6.1.5. Final plug-in, I cannot find the method to set the dao java file name through the “filepattern” attribute.
In the plug-in "hibernate tools maven plugin" 5.6.12. Final, there is no method to set the dao java file name.

Although the project has stopped, you should know more about the setting method than I do, and you know more about the project than I do. If you can help, thank you very much

**Comment by mmm8955405** [comment]
Among all the materials available, the following are all the Maven plug-in methods I have tried:


			
		    
		    
		    
		    
			
			
			
			<plugin>
		        <groupId>org.apache.maven.plugins</groupId>
		        <artifactId>maven-antrun-plugin</artifactId>
		        <executions>
		            <execution>
		              <phase>generate-sources</phase>
		              <goals>
							<goal>run</goal>
					  </goals>
		              <configuration>
		                <target>
		                  <taskdef name="hibernatetool"
		                           classname="org.hibernate.tool.ant.HibernateToolTask"
		                           classpathref="maven.dependency.classpath"/>
		                           
		                  <hibernatetool destdir="${project.basedir}/target/generated-sources/repository">
						  	 <jdbcconfiguration
							 	propertyfile="${project.basedir}/src/main/resources/generate/jpa/hibernate.properties"
					  			revengfile="${project.basedir}/src/main/resources/generate/jpa/hibernate.reveng.xml"
					  			packagename="tech.bcnew.jpa"
					  			detectManytoMany="false">
  							 </jdbcconfiguration>
							 <hbm2java jdk5="true" ejb3="true"></hbm2java>
							 
							 <hbmtemplate
							   templatepath="${project.basedir}/src/main/resources/generate/jpa"
							   template="DaoHome.ftl"
							   filepattern="{package-name}/daos/{class-name}JpaDao.java">
							    <property key="jdk5" value="false" />
  								<property key="ejb3" value="false" />
							 </hbmtemplate>
							 
						</hibernatetool>
		                </target>
		              </configuration>
		              
		            </execution>
		          </executions>
		          <dependencies>
			          <dependency>
			            <groupId>org.hibernate.tool</groupId>
			            <artifactId>hibernate-tools-orm</artifactId>
			            <version>6.1.5.Final</version>
			          </dependency>
		          </dependencies>
		          
	        </plugin>

**Comment by mmm8955405** [comment]
”filePattern "does not work in" maven-antrun-plugin "and" hibernate-tools-maven-plugin "
