### ISSUE TITLE
revengStrategy

### ISSUE THREAD

**Issue by RBaldi** [stadler/hibernate-tools-maven-plugin#2]
Hi, I try to use custom revengStrategy and set my class ( class extends DelegatingReverseEngineeringStrategy ), but when I launch hibernate-tools:hbm2java on my project the result is : CustomRevengeStrategy not instanced.

Is that a bug or I set incorrectly revengStrategy?

Best regards.

**Comment by stadler** [comment]
Hi
As mentioned in the README.md, this project is no longer active as it has been integrated into hibernate tools itself.
You may find the latest version of hibernate-tools here: https://github.com/hibernate/hibernate-tools
To create issues for hibernate-tools see: https://github.com/hibernate/hibernate-tools/blob/main/contribute.md
